local h = require("tests.helpers")
local ring = require("clipring.ring")

describe("clipring.ring", function()
  before_each(function()
    h.reset()
  end)

  it("adds yanks to the front of the list", function()
    ring.add({ "first" }, "v")
    ring.add({ "second" }, "v")
    assert.are.equal(2, ring.count())
    assert.are.equal("second", ring.get(1).lines[1])
    assert.are.equal("first", ring.get(2).lines[1])
  end)

  it("respects max_entries", function()
    require("clipring.config").setup({ max_entries = 2, deduplicate = false, min_length = 1 })
    ring.add({ "a" }, "v")
    ring.add({ "b" }, "v")
    ring.add({ "c" }, "v")
    assert.are.equal(2, ring.count())
    assert.are.equal("c", ring.get(1).lines[1])
    assert.are.equal("b", ring.get(2).lines[1])
  end)

  it("deduplicates and moves existing entry to front", function()
    ring.add({ "a" }, "v")
    ring.add({ "b" }, "v")
    ring.add({ "a" }, "v")
    assert.are.equal(2, ring.count())
    assert.are.equal("a", ring.get(1).lines[1])
    assert.are.equal("b", ring.get(2).lines[1])
  end)

  it("skips duplicate when already newest", function()
    ring.add({ "same" }, "v")
    ring.add({ "same" }, "v")
    assert.are.equal(1, ring.count())
  end)

  it("removes entries by index", function()
    ring.add({ "a" }, "v")
    ring.add({ "b" }, "v")
    assert.is_true(ring.remove(1))
    assert.are.equal(1, ring.count())
    assert.are.equal("a", ring.get(1).lines[1])
  end)
end)
